name: Run Python script

on:
  schedule:
    - cron: '13 20 * * *' # Расписание (здесь - каждый день в 00:00 UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Укажите вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/requirements.txt

    - name: Run Python script
      run: python $GITHUB_WORKSPACE/bot.py # Укажите путь к вашему скрипту
