name: Run Python script

on:
  schedule:
    - cron: '24 20 * * *' # Расписание (каждый день в 20:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Замените '3.x' на вашу версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot

    - name: Run Python script
      run: python bot.py # Укажите путь к вашему скрипту
